from setuptools import setup

setup(
    name='jupyterhub-duoauthenticator',
    version='1.0',
    description='Duo Two-Factor Authentication for JupyterHub',
    url='https://github.com/unlhcc/duoauthenticator',
    author='Adam Caprez',
    author_email='acaprez2@unl.edu',
    license='GPLv3',
    packages=['duoauthenticator'],
    include_package_data=True,
    data_files = [('share/jupyterhub/templates',
                 ['share/jupyterhub/templates/duo.html']),
                 ('share/jupyterhub/static/components/duo/css',
                 ['share/jupyterhub/static/components/duo/css/Duo-Frame.css']),
                 ('share/jupyterhub/static/components/duo/js',
                 ['share/jupyterhub/static/components/duo/js/Duo-Web-v2.js',
                  'share/jupyterhub/static/components/duo/js/Duo-Web-v2.min.js']),
    ],
    install_requires=[
        'duo_web',
        'jupyterhub',
    ],
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Natural Language :: English',
        'Operating System :: Unix',
        'Topic :: System :: Systems Administration :: Authentication/Directory',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
    ],
)
